### ISSUE TITLE
GUI Version

### ISSUE THREAD

**Issue by RyanBram** [akesterson/rvpacker#7]
Hi,
Your tool seems very useful for my project. Can you consider a simple GUI version, because I have no idea how to use it?
At least it will be nice if there is a complete binary although using command line, so we doesn't need to search every package needed.
Thanks

**Comment by akesterson** [comment]
Hi there. There are currently no plans to add any new features to rvpacker. I have built an example RPG Maker project, [RPGSkeleton](https://github.com/akesterson/RPGSkeleton), which provides a simplified workflow for managing the packing and unpacking of data on checkin and checkout, and instructions for both technical and non-technical users. If you need some more help getting it to work, feel free to reach out to me directly.
